name: Deploy to Github Pages
#Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
jobs:
  deploy-to-github-pages:
     #use ubuntu-latest image to run steps on
       runs-on: ubuntu-latest
       steps:
         #uses github checkout action to checkout code from the master branch
           - uses: actions/checkout@v2
             #sets up .net 5 sdk
           - name: Setup .NET 5.0 SDK
             uses: actions/setup-dotnet@v1.7.2
             with:
               dotnet-version: 5.0.100
           
           - name: Publish .Net Project
             run: dotnet publish CeraUnaVolta.sln -c Release -o release --nologo
            
            # changes the base-tag in index.html from '/' to 'CeraUnaVolta' to match GitHub Pages repository subdirectory
           - name: Change base-tag in index.html from / to CeraUnaVolta
             run: sed -i 's/<base href="\/" \/>/<base href="\/CeraUnaVolta\/" \/>/g' release/wwwroot/index.html
            
           - name: Change href tag from / to CeraUnaVolta in FullPage.razor
             run: sed -i 's/href="\/"/href="\/CeraUnaVolta\/"/g' release/wwwroot/index.html
                        
            # copy index.html to 404.html to serve the same file when a file is not found
           - name: copy index.html to 404.html
             run: cp release/wwwroot/index.html release/wwwroot/404.html
            
            # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
           - name: Add .nojekyll file
             run: touch release/wwwroot/.nojekyll
           
           - name: Commit wwwroot to Github Pages
             uses: JamesIves/github-pages-deploy-action@3.7.1
             with:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               BRANCH: gh_pages
               FOLDER: release/wwwroot
